language: java
sudo: required
dist: trusty
jdk:
  - oraclejdk8
  - oraclejdk9
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script: ./gradlew -I gradle/travis.gradle check
